<a href="https://colab.research.google.com/github/subhash-ranjan/numpy-pg/blob/main/numpy_pg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int16')

In [ ]:
# Get shape
a.shape

(2, 3)

In [ ]:
# Get type
a.dtype

dtype('int64')

In [ ]:
# Get size
a.itemsize


2

In [ ]:
# Get Total size

a.size * a.itemsize

# or 

a.nbytes

6

Access/Modify items

In [ ]:
item = np.array([[1,33,4,6,8,77],[31,44,6,7,9,89]])

# Get 44
item[1,1]

# Get a specific row ':' for all columns
item[0,:]

# Get by [startindex:endindex:stepsize]
# get [33,6,77]
item[0,1:6:2]

# get [8,9] allrows: 4th col
item[:,-2]




array([8, 9])

3D array

In [ ]:
b = np.array([[[1,4],[5,6]],[[8,9],[2,3]]])
b

array([[[1, 4],
        [5, 6]],

       [[8, 9],
        [2, 3]]])

In [ ]:
# Get the item 4
b[0,0,1]

4

Initialize different arrays

In [ ]:
# All 0s matrix
np.zeros((2,3),dtype='int32')

# Other numbers: (full)
np.full((2,3), 44, dtype='float')

# By shape: (full)
np.full(a.shape, 66)

# Other numbers: (full_like)
np.full_like(a,4,  dtype='float')

# Random decimal numbers
np.random.rand(2,3)

# Random decimal numbers: (random_sample)
np.random.random_sample(a.shape)

# The identity matrix
np.identity(4)

# Repeat an array
arr= np.array([[1,2,3]])
arr1 = np.repeat(arr,3, axis=1)
arr1



array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

Deep copy

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[1] =100


array([1, 2, 3])

Mathematics

In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a+b

# Take the sin
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])

Linear algebra

In [3]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

Stats

In [9]:
stats = np.array([[1,2,3],[4,5,6]])

# Min
np.min(stats, axis=0)
np.max(stats, axis=1)

#Sum
np.sum(stats)


21

Reorganizing arrays

In [18]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((4,2))

# Vertically stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

# Horizontally stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack([v1,v2,v1])



array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

Miscellaneous

In [24]:
# Load from files
filedata = np.genfromtxt('data.txt', delimiter=',')

# Convert to int type
filedata = filedata.astype('int32')

# Boolean masking and advance indexing
filedata[filedata>50]



array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)